version: '3.8'

services:
  webserver:
    image: nginx:latest
    container_name: wassermusik_${PROJECT_NAME}  # Dynamic container name based on the project
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - runner
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wassermusik_${PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.wassermusik_${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.wassermusik_${PROJECT_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.wassermusik_${PROJECT_NAME}.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"  # Label to allow Watchtower updates

networks:
  runner:
    external: true
