version: '3.8'

services:
  webserver:
    image: nginx:latest
    container_name: nginx_webserver
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

networks:
  webnet:
    driver: bridge