version: '3.8'

services:
  webserver:
    image: nginx:latest
    container_name: wassermusik
    ports:
      - "3562:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - runner
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wassermusik.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.wassermusik.entrypoints=websecure"
      - "traefik.http.routers.wassermusik.tls.certresolver=myresolver"
      - "traefik.http.services.wassermusik.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"  # Label to allow Watchtower updates

networks:
  runner:
    external: true